version: '3'
services:
    php-fpm-beer:
        build: docker/php/
        volumes:
            - './:/usr/share/nginx/html'
        networks:
        - traefik
    mariadb-beer:
        image: 'mariadb:10.3'
        volumes:
            - './docker/database:/var/lib/mysql'
        environment:
            - MYSQL_DATABASE=docker
            - MYSQL_USER=docker
            - MYSQL_PASSWORD=s3cr3t
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        networks:
        - traefik
    nginx-beer:
        build: docker/nginx/
        volumes:
            - './:/usr/share/nginx/html'
        networks:
        - traefik
        labels:
        - "traefik.backend=beeronaute"
        - "traefik.frontend.rule=Host:beer.narah.io"
        - "trafik.enable=true"
        - "traefik.port=80"
        - "traefik.protocol=http"
        - "traefik.frontend.entryPoints=http"
networks:
  traefik:
    external: true
